# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='cover/%Y/%m/%d')),
                ('status', models.IntegerField(choices=[(1, 'current show'), (2, 'ended / cancelled'), (3, 'on hiatus')], default=1)),
                ('aired_from', models.DateField(default=django.utils.timezone.now)),
                ('aired_to', models.DateField(blank=True, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='shows', to='tvshows.Category')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='tvshow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tvshows.Show'),
        ),
    ]
