# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='episodes_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='show',
            name='series_no',
            field=models.IntegerField(default=1),
        ),
    ]
