# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tvshow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tvshows.Show'),
        ),
    ]
