# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_article_tvshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='article/%Y/%m/%d'),
        ),
    ]
